# Generated by Django 4.2.4 on 2023-09-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mapaap", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="banners/")),
                ("alt_text", models.CharField(max_length=255)),
            ],
        ),
    ]
